name: streamy
version: 0.2.2-dev.1
description: >
  An experimental client API generator for services described using Google's API
  discovery format (https://developers.google.com/discovery/v1/using#discovery-doc).
  The generator comes with templates that generate streaming API via dart:async's
  Stream object.
authors:
- Alex Rickabaugh <arick@google.com>
- Yegor Jbanov <yjbanov@google.com>
homepage: https://github.com/google/streamy-dart
environment:
  sdk: '>=1.6.0'
dependencies:
  barback: ">=0.15.0 <0.16.0"
  browser: ">=0.10.0 <0.11.0"
  mustache: ">=0.1.5 <0.2.0"
  args: ">=0.12.0 <0.13.0"
  fixnum: ">=0.9.0 <0.10.0"
  observe: ">=0.12.0 <0.13.0"
  quiver: ">=0.18.0 <0.20.0"
  yaml: ">=2.0.0 <3.0.0"
dev_dependencies:
  analyzer: ">=0.22.0 <0.24.0"
  path: ">=1.3.0 <1.4.0"
  protobuf: ">=0.3.4 <0.4.0"
  unittest: ">=0.11.0 <0.12.0"
  benchmark_harness: ">=1.0.0 <2.0.0"
  intl: ">=0.11.0 <0.12.0"
transformers:
- streamy
- $dart2js:
    $include: test/benchmark_html.dart
- $dart2js:
    $include: test/test_in_browser.dart
