name: streamy
version: 0.0.7
description: >
  An experimental client API generator for services described using Google's API
  discovery format (https://developers.google.com/discovery/v1/using#discovery-doc).
  The generator comes with templates that generate streaming API via dart:async's
  Stream object.
authors:
- Alex Rickabaugh <arick@google.com>
- Yegor Jbanov <yjbanov@google.com>
homepage: https://github.com/google/streamy-dart
environment:
  sdk: '>=1.4.0'
dependencies:
  barback: any
  browser: any
  mustache: ">=0.1.5"
  args: ">=0.9.0"
  meta: ">=0.8.8"
  fixnum: ">=0.9.0"
  observe: ">=0.9.1 <=0.10.0"
  quiver: ">=0.14.0"
  yaml: any
dev_dependencies:
  analyzer: any
  path: any
  protobuf: any
  unittest: any
  benchmark_harness: ">=1.0.0"
  intl: any
transformers:
- streamy
- $dart2js:
    $include: nonexistent/path
